[project]
name = "resume"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["typer[all]"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = ["pytest"]

[tool.setuptools.packages.find]
where = ["src"]
